language: python
python:
  - "3.8"
cache: pip

os:
  - linux

services:
  postgresql

install:
  - pip install -e .

script:
  - create-db odmf-test
  - odmf configure --dbname odmf-test --port 8080
  - odmf make-db --p voxonacawiru
  - odmf test-db
  - odmf start &
  # Timouts to let the server start up
  - sleep 7
  # Run acceptance tests
  - cd tests; ./run_tests

