language: python
python:
  - "3.8"
cache: pip

os:
  - linux

services:
  postgresql

install:
  - pip install -e .

script:
  - create-db odmf-test
  - odmf configure --dbname odmf_test --dbuser xxx --dbpass xxx --dbhost localhost --port 8080
  - odmf make-db
  - odmf test-db
  # Timouts to let the server start up
  - sleep 7
  # Run acceptance tests
  - cd tests; ./run_tests

# TODO: also include postgres-scripts
