# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ODMF - Observatory Data Management Framework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install postgresql client lib
      run: |
        apt update
        apt install -y libpq-dev
        apt install -y postgresql-client
    - name: Create venv
      run: python3.9 -m venv venv
    - name: Install dependencies
      run: |
        venv/bin/python -m pip install --upgrade pip
        venv/bin/pip install wheel psycopg2-binary
    - name: Test DB connection
      run: venv/bin/python tests/database_connection.py
    - name: Make ODMF
      run : |
        venv/bin/pip install -e .
        mkdir odmf-test
        cd odmf-test
    - name: Configure ODMF
      run: |
        venv/bin/odmf configure "postgresql://postgres:password@localhost:5432/postgres"  --port 8080
        venv/bin/odmf test-config
    - name: Make ODMF Database
      run: |
        venv/bin/odmf make-db -p testpw
        venv/bin/odmf test-db
    - name: Test the server
      if: ${{ github.ref == 'refs/heads/master' }}
      run : |
        venv/bin/odmf start &
        sleep 10
        curl localhost:8080/login
