# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  paths: [ .github/workflows ]
    

jobs:
  runner-job:

    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        environment:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
     - uses: actions/checkout@v2
     - name: Set up Python 3.9
       uses: actions/setup-python@v2
       with:
         python-version: 3.9
     - name: Install postgresql client lib
       run: apt-get update && apt-get install -y libpq-dev postgresql-client
     - name: Test psql client
       run: psql -d postgresql://postgres:postgres@localhost -c '\l'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install wheel setuptools
#        pip install -r requirements.txt
#    - name: Make ODMF
#      run : |
#        pip install .
#    - name: Make Database
#      run: |
#        odmf configure postgresql://db_user:pwd@localhost:5432/odmf --port 8000
#        cat config.yml
#        odmf db-create -p testpw
#        odmf db-test
